config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :rooms do
    collection do
      get :check_availability
    end
  end
  resources :bookings

  root :to => 'bookings#home'
  get 'home' => "bookings#home"

end

app/models/booking.rb
class Booking < ActiveRecord::Base

  enum room_type: ["Deluxe Rooms", "Luxury Rooms", "Luxury suites","Presidential Suites"]

  belongs_to :room
  belongs_to :user

  before_validation :rooms_are_available
  before_create :add_cost

  validate :last_date_greater_than_start_date_and_smaller_six_month
  validates :user_id, :start_date, :last_date, presence: true
  validates_format_of :start_date, :last_date, :with => /\d{4}\-\d{2}\-\d{2}/, :message => "^Date must be in the following format: mm/dd/yyyy"


  def last_date_greater_than_start_date_and_smaller_six_month
    if dates_is_blank?
      return true
    elsif Date.today > start_date.to_date
      errors.add(:start_date, "check in date should be greater or equal to today's date")
    # start_date should be smaller than 6 months
    elsif Date.today + 6.months < start_date.to_date
      errors.add(:last_date, "Check in date should be smaller than 6 months")
      # last_date should be smaller than 6 months
    elsif Date.today + 6.months < last_date.to_date
      errors.add(:last_date, "Check out date should be smaller than 6 months")
    # last_date should be greater than start_date
    elsif last_date.to_date == start_date.to_date
      errors.add(:last_date, "check out date should be greater than Check in Date")
    # last_date should be greater than start_date
    elsif last_date.to_date < start_date.to_date
      errors.add(:last_date, "check out date should be greater than Check in Date")
    end
  end

  # get the all the room_id which room are booked in between start_date and last_date
  def self.excluded_ids(start_date,last_date)
    # if array is empty return  true else return the array
    existing_booking_ids = Booking.where("Date(start_date) < ? AND Date(last_date) > ? ", last_date,start_date).pluck(:room_id)
    if existing_booking_ids.blank?
      return false
    else
      return existing_booking_ids
    end
  end

  def rooms_are_available
    rooms = Room.avail_rooms(start_date, last_date, room_type).limit(1)
    if rooms.length > 0
      self.room_id = rooms.first.id
    else
      errors.add(:num_of_user, "Rooms are not available #{room_type}")
    end
  end

  def dates_is_blank?
    if start_date.blank? || last_date.blank?
      return true
    end
  end

  def room_type_int
    self.class.room_types[self.room_type]
  end

  def add_cost
    self.cost = (self.last_date - self.start_date).to_i * self.room.price
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  enum room_type: ["Deluxe Rooms", "Luxury Rooms", "Luxury suites","Presidential Suites"]
  has_and_belongs_to_many :bookings

  def self.avail_rooms(start_date, last_date, room_type)
    if Booking.excluded_ids(start_date, last_date)
      self.where("room_type = ? AND id NOT IN (?)", Room.room_types[room_type], Booking.excluded_ids(start_date, last_date))
    else
      self.where("room_type = ?", Room.room_types[room_type])
    end
  end

  def room_type_int
    self.class.room_types[self.room_type]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :rememberable
  # include DeviseTokenAuth::Concerns::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy, :index, :show]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  # GET /bookings
  def index
    @bookings = current_user.bookings.includes(:room).paginate(page: params[:page], per_page: 10)
  end

  def home
    @booking = Booking.new
    @bookings = Booking.all
  end

  def show
    if @booking
      @room = @booking.room
    else
      redirect_to root_path
    end
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(room_type: params[:room_type].to_i)
  end

  def create
    @booking = current_user.bookings.build(booking_params)
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
      else
        format.html { render :new}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = current_user.bookings.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params["booking"]["room_type"] = params["booking"]["room_type"].to_i if params["booking"]["room_type"].present?
      params.require(:booking).permit(:room_type, :room_id, :start_date, :last_date, :num_of_user, :cost)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :check_availability]
  before_action  :authorize, except: [:index, :show, :check_availability]
  include ApplicationHelper
  def index
    @rooms = Room.all
    @room = Booking.new
  end

  def show
    @booking = Booking.new(room_type:@room.room_type)
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end


  def check_availability
    @errors = []
    if last_date_greater_than_start_date_and_smaller_six_month(params[:arrival], params[:departure])
      return false
    # last_date should be smaller than 6 months
    elsif params[:room_type].empty?
      @deluxe = Room.avail_rooms(params[:arrival], params[:departure], 'Deluxe Rooms').count
      @lux_room = Room.avail_rooms(params[:arrival], params[:departure], 'Luxury Rooms').count
      @lux_suite = Room.avail_rooms(params[:arrival], params[:departure], 'Luxury suites').count
      @pres_suite = Room.avail_rooms(params[:arrival], params[:departure], 'Presidential Suites').count
    else
      @rooms = Room.avail_rooms(params[:arrival], params[:departure], params[:room_type]).count
    end
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:price, :rno, :room_type)
    end

    def last_date_greater_than_start_date_and_smaller_six_month(start_date, last_date)
      if Date.today > start_date.to_date
        @errors.push(:start_date, "check in date should be greater or equal to today's date")
      # last_date should be smaller than 6 months
      elsif Date.today + 6.months < last_date.to_date
        @errors.push(:last_date, "Check out date should be smaller than 6 months")
      # last_date should be greater than start_date
      elsif last_date.to_date == start_date.to_date
        @errors.push(:last_date, "check out date should be greater than Check in Date")
      # last_date should be greater than start_date
      elsif last_date.to_date < start_date.to_date
        @errors.push(:last_date, "check out date should be greater than Check in Date")
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def admin?
		current_user == User.first
	end

	def authorize
    unless admin?
      flash[:error] = "unauthorized access"
      redirect_to home_path
      false
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/_booking.html.erb
<div class = "booking">
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Booking Detail</h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class=" col-md-12 col-lg-12 ">
          <table class="table table-user-information">
            <tbody>
              <tr>
                <td>Room No</td>
                <td><%= @booking.room.rno%></td>
              </tr>
              <tr>
                <td>Check In </td>
                <td><%= @booking.start_date%></td>
              </tr>
              <tr>
                <td>Check Out </td>
                <td><%= @booking.last_date%></td>
              </tr>
              <tr>
                <td>Room Type </td>
                <td><%= @booking.room.room_type%></td>
              </tr>
              <tr>
                <td>Cost per room </td>
                <td><%= @booking.room.price%></td>
              </tr>
              <tr>
                <td>Total Cost </td>
                <td><%= @booking.cost%></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/_form.html.erb
<section class="site-section">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <h2 class="mb-5">Reservation Form</h2>
          <%= form_for(@booking) do |f| %>

          <% if @booking.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

              <ul>
                <% @booking.errors.messages.each do |attribute, message| %>
                  <li><%= message.first %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <label for="">Room Type</label>
            <div style="position: relative;">
              <%= f.select :room_type, options_for_select(Booking.room_types, selected: params[:room_type]), {}, {class: 'form-control'}%>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6 form-group">
              <label for="">Check In Date</label>
              <div style="position: relative;">
                <%= f.date_field :start_date, class: "form-control", value: params[:start_date]%>
              </div>
            </div>

            <div class="col-sm-6 form-group">
              <label for="">Check Out Date</label>
              <div style="position: relative;">
                <%= f.date_field :last_date, class: "form-control", value: params[:last_date]%>
              </div>
            </div>
          </div>

          <div class="row">


            <div class="col-md-6 form-group">
              <label for="room">Guests</label>
              <%= f.select :num_of_user, {1 => 1, 2 => 2, 3 => 3, 4 => 4}, {class: "form-control"} %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 form-group">
              <%= f.submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/bookings/_slider.html.erb
<div class="test" id="testimonials">
  <div class="container">
    <div class="test-top">
      <section class="slider">
        <div class="flexslider">
          <ul class="slides">
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_0", size:"200"), new_booking_path(room_type:0)%>
                  <p>very good rooms.</p>
                  <h4>Deluxe Rooms - Queen Size Bed</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1", size:"200"), new_booking_path(room_type:1)%>
                  <p>very good rooms.</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                   <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_2", size:"200"), new_booking_path(room_type:2)%>
                  <p>very good rooms.</p>
                  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
                   <p><%= link_to 'Book Now', new_booking_path(room_type:2), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_3", size:"200"), new_booking_path(room_type:3)%>
                  <p>very good rooms.</p>
                  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:3), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_0_1", size:"200"), new_booking_path(room_type:0)%>
                  <p>very good rooms.</p>
                  <h4>Deluxe Rooms - Queen Size Bed</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1_1", size:"200"), new_booking_path(room_type:1)%>
                  <p>very good rooms.</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
            <li>
              <div class="test-one">
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_2_1", size:"200"), new_booking_path(room_type:2)%>
                  <p>very good rooms.</p>
                  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:2), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_3_1", size:"200"), new_booking_path(room_type:3)%>
                  <p>very good rooms.</p>
                  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:3), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="col-md-4 test-left">
                  <%= link_to image_tag("room_1", size:"200"), new_booking_path(room_type:1)%>
                  <p>very good rooms.</p>
                  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
                  <p><%= link_to 'Book Now', new_booking_path(room_type:1), class: 'btn btn-primary btn-sm'%></p>
                </div>
                <div class="clearfix"></div>
              </div>
            </li>
          </ul>
        </div>
      </section>
    </div>
  </div>
</div>
  <!--end-test-->

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/home.html.erb
<body>
  <!--start-header-->
  <section class="site-hero overlay" data-stellar-background-ratio="0.5" style="background-image: url(assets/big_image_1.jpg);">
  <div class="container">
    <div class="row align-items-center site-hero-inner justify-content-center">
      <div class="col-md-12 text-center">

        <div class="mb-5">
          <h1>Welcome To Our Luxury Rooms</h1>
          <p>Discover our world's #1 Luxury Room For VIP.</p>
          <p><%= link_to 'Book Now', new_booking_path, class: 'btn btn-primary'  %></p>
        </div>

      </div>
    </div>
  </div>
</section>

  <!-- <div class="banner">
    <div class="container">
      <div class="banner-top">
        <%#= render "form"%>
      </div>
    </div>
  </div> -->
  <%= render "slider" %>
</body>

app/views/bookings/index.html.erb
<div id="wrap">
  <div id="main" class="container clear-top">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Email</th>
          <th>Room No</th>
          <th>Start Date</th>
          <th>Last Date</th>
          <th>Guest</th>
          <th> Show <th>
        </tr>
      </thead>
      <% @bookings.each do |booking|%>
        <tr>
          <td> <%= booking.user.email %></td>
          <td> <%= link_to booking.room.rno, booking %> </td>
          <td><%= booking.start_date %></td>
          <td><%= booking.last_date%></td>
          <td><%= booking.num_of_user%></td>
          <td> <%= link_to "show", booking %> </td>
        </tr>  
      <%end%>
    </table>
    <%=will_paginate @bookings%>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="services">
  <div class="container">
    <div class="col-md-6 services-left">
      <%= render "rooms/room_#{@booking.room_type_int}"%>
    </div>
    <div class="col-md-6 services-right" style = "background-color: #ADD8E6;">
      <%= render "bookings/form"%>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="services">
  <div class="container">
    <div class="col-md-12 services-right">
      <h3> Booking Detail</h3>
        <%= render "booking"%>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillEasyHotel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag("application") %>
  <%= javascript_include_tag("jquery.flexslider")%>
  <%= csrf_meta_tags %>

	<title>Paix a Hotel Category Flat Bootstarp responsive Website Template | Home :: w3layouts</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<!---- start-smoth-scrolling---->

	<script type="text/javascript">
	      jQuery(document).ready(function($) {
	        $(".scroll").click(function(event){   
	          event.preventDefault();
	          $('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
	        });
	      });
	    </script>
	<!--start-smoth-scrolling-->
</head>
<body>
  <%= render "shared/navigation_bar" %>
		<%= yield %>
  <%= render "shared/footer"%>
</body>
</html>

app/views/rooms/_available_rooms.html.erb
<% if @errors.any? %>
  <div id="error_explanation">
    <ul>
      <%# @errors.each do | message| %>
        <li><%= @errors.last %></li>
      <%# end %>
    </ul>
  </div>
<% elsif params[:room_type].empty? %>
  <table class="col-sm-12 ">
    <thead>
      <tr>
        <th>Room Type</th>
        <th>Available Rooms</th>
        <th>Book now</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Deluxe Rooms</td>
        <td><%=@deluxe%></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type:0, start_date: params[:arrival], last_date: params[:departure]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <td>Luxury Rooms</td>
        <td><%=@lux_room%></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type:1, start_date: params[:arrival], last_date: params[:departure]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <td>Luxury suites</td>
        <td><%=@lux_suite%></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type:2, start_date: params[:arrival], last_date: params[:departure]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
      <tr>
        <td>Presidential Suites</td>
        <td><%=@pres_suite%></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type:3, start_date: params[:arrival], last_date: params[:departure]), class: 'btn btn-primary btn-sm mb-10'%></td>
      </tr>
    </tbody>
  </table>
<% else %>
<table class="col-sm-12 ">
    <thead>
      <tr>
        <th>Room Type</th>
        <th>Available Rooms</th>
        <th>Book now</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= params[:room_type]%></td>
        <td><%=@rooms%></td>
        <td><%= link_to 'Book Now', new_booking_path(room_type:0), class: 'btn btn-primary btn-sm'%></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/rooms/_check_availability.html.erb
<%= form_tag("/rooms/check_availability", method: "get", remote: true) do %>

  <div class="row">
    <div class="col-sm-3 form-group">
      <label>Check in</label>
      <input type="date" name="arrival" class="form-control">
    </div>
    <div class="col-sm-3 form-group">
      <label>Check out</label>
      <input type="date" name="departure" class="form-control"  min = today>
    </div>
    <div class="col-sm-3 form-group">
      <label>Room Type</label>
      <select name="room_type" id="room" class="form-control">
        <option value="">Select Room Type</option>
        <option value="Deluxe Rooms">Deluxe Rooms</option>
        <option value="Luxury Rooms">Luxury Rooms </option>
        <option value="Luxury suites">Luxury suites</option>
        <option value="Presidential Suites">Presidential Suites</option>
      </select>
    </div>
    <div class="col-sm-3 form-group">
      <br>
      <button type="submit" class="btn btn-default">check</button>
    </div>
  </div>
<%end %>

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :rno %><br>
    <%= f.number_field :rno %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.number_field :room_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_room_0.html.erb
<div class="services-one border">
  <div class="flexslider flexslider-padding">
    <div>
      <%= link_to image_tag("room_0", class: "img-responsive",height: 300, width: 450), new_booking_path(room_type:0)%>
    </div>
    <div class="clearfix"></div>
  </div>

  <h4>Deluxe Rooms - Queen Size Bed</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>Queen Size Bed</li>
    <li>Beautifu Views</li>
    <li>7000 per night</li>
  </ul>
</div>

app/views/rooms/_room_1.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <div>
        <%= link_to image_tag("room_1", class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:1)%>
      </div>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Luxury Rooms - Queen Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>Queen Size Bed</li>
    <li>Swimming Pool</li>
    <li>8500 per night</li>
  </ul>
</div>

app/views/rooms/_room_2.html.erb
<div class="services-one">
  <div class="flexslider flexslider-padding">
    <div>
      <%= link_to image_tag("room_2",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:2)%>
    </div>
    <div class="clearfix"></div>
  </div>
  <h4>Luxury Suites - King Size Bed and Pool Facing</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>King Size Bed</li>
    <li>Swimming Pool</li>
    <li>12000 per Night</li>
  </ul>
</div>

app/views/rooms/_room_3.html.erb
<div class="services-one">
  <section class="slider">
    <div class="flexslider flexslider-padding">
      <div>
        <%= link_to image_tag("room_3",class: "img-responsive", height: 300, width: 450), new_booking_path(room_type:3)%>
      </div>
      <div class="clearfix"></div>
    </div>
  </section>
  <h4>Presidential Suites - King Size Bed, Pool Facing with a Gym</h4>
  <p>The Deluxe rooms are located on the upper floors, offering beautiful views of the city of São Paulo, a privilege offered by few hotels. Facilities are focused on guest comfort and functionality, and services to make your stay unforgettable.</p>

  <p>Enjoy the modern décor and well-designed layout of this room measuring 27 m2 in one of the best hotels in São Paulo. </p>
  <p>Enjoy also the comfort provided by the soft, inviting bed, as well as the television with international channels..</p>
  <ul>
    <li>King Size Bed</li>
    <li>Swimming Pool</li>
    <li>20000 per night</li>
  </ul>
  <div class="clearfix"></div>
</div>

app/views/rooms/check_availability.js.erb
$("#available").html("<%= j render(partial: 'available_rooms') %>");

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
  <div class="services">
    <div class="container">

      <div>
        <h3>Check Availability</h3>
        <%=render 'check_availability'%>
      </div>
      <div id = 'available'>

      </div>
      <div class="services-top heading">
        <h3>Room categories</h3>
      </div>
      <br><br>
      <div class="services-bottom">
        <div class="col-md-6 services-left">
          <%= render "room_0" %>
          <%= render "room_1" %>
        </div>
        <div class="col-md-6 services-right">
          <%= render "room_2" %>
          <%= render "room_3" %>
        </div>
      </div>
    </div>
  </div>
  <!--end-services-->
  <!--start-special-->
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="services">
  <div class="container">
    <div class="col-md-6 services-left">
      <%= render "room_#{@room.room_type_int}"%>
    </div>
    <div class="col-md-6 services-right" style = "background-color: #ADD8E6;">
      <%= render "bookings/form"%>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- <div class="footer">
  <div class="container">
  <div class="touch-top heading">
      <h3>FOLLOW US</h3>
    </div>
  </div>
  <script type="text/javascript">
                $(document).ready(function() {

                  $().UItoTop({ easingType: 'easeOutQuart' });

                });
              </script>
  <a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
</div> -->

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">HOTEL</a>
    </div>
    <nav class="navigation row" id = "navigation_bar">
      <span class="menu"></span>
      <ul class="nav navbar-nav" >
        <li ><a href="/"  class="active hvr-bounce-to-bottom">Home</a></li>
        <li><a href="/rooms" class="hvr-bounce-to-bottom">Rooms</a></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Bookings', bookings_path,class: "hvr-bounce-to-bottom" %></li>
          <li>
            <a class="hvr-bounce-to-bottom" ><%= current_user.email %></a>
          </li>
          <li><%= link_to 'Log out', destroy_user_session_path,class: "hvr-bounce-to-bottom", method: :delete %></li>

          </li>
        <% else %>
           <li><a href="/users/sign_up" class="hvr-bounce-to-bottom"> Sign Up</a></li>
           <li><a href="/users/sign_in" class="hvr-bounce-to-bottom"> Login</a></li>
        <% end %>
      </ul>
    </nav>
  </div>
</nav>